[package]
name = "calendar_mirror"
version = "0.1.0"
authors = ["pi"]
edition = "2018"

[dependencies]
url="1.7.2"
serde={version = "1.0.92", features = ["derive"]}
serde_json="1.0.39"
reqwest="0.9.18"
chrono="0.4"
graphviz="1.0.0"